### ISSUE TITLE
Generated (section) ids contain full path

### ISSUE THREAD

**Issue by myabc** [livingstyleguide/livingstyleguide#133]
Affects LSG `2.0.0.alpha.6`

Examples:

```html
<section id="/home/rof/src/github/eurucamp/livingstyleguide-eurucamp/source/stylesheets/components/team-page">...</section>
```

```html
<section id="/Users/alexbcoles/git-repos/openproject/app/assets/stylesheets/../stylesheets/content/buttons">...</section>
```

**Comment by myabc** [comment]
@hagenburger –

1. we should probably strip the project base path.
2. while I think slashes are now considered OK in HTML 5 ( http://www.w3.org/TR/html5/dom.html#the-id-attribute), they make things for styling/JS interaction more difficult.

**Comment by hagenburger** [comment]
I plan to work on load paths for the next release and this should be part of it.

**Comment by hagenburger** [comment]
Done
