### ISSUE TITLE
Newest alpha not working with Rails 4.1

### ISSUE THREAD

**Issue by eljojo** [livingstyleguide/livingstyleguide#139]
Hi,
I was trying to run the livingstyleguide in my application but couldn't get it to work.
The only thing I was seeing is:
![screen shot 2015-05-18 at 19 08 43](https://cloud.githubusercontent.com/assets/491230/7685948/84bb08be-fd92-11e4-886e-8d31612eb739.png)

I managed to reproduce the error in the example application: https://github.com/livingstyleguide/examples/compare/master...eljojo:bug

I updated more gems than needed, (and I'm not fully sure what causes the problem), but I know for sure that the "bug" branch in my fork works with the version 1.2.2 and not with 2.0.0.alpha.7.
More specifically, [this was the commit that broke it](https://github.com/livingstyleguide/examples/commit/a46bc4ab2c7a2426b0a19d89efc9a2505fe40317).

**Comment by eljojo** [comment]
@myabc pointed out to me that i'm not using the new syntax.
maybe it's time to update the documentation in the README?

**Comment by myabc** [comment]
@eljojo it is up-to-date, you just have to know to look at the `v2` branch: https://github.com/livingstyleguide/livingstyleguide/blob/v2/README.md

**Comment by eljojo** [comment]
achso! well then all my fault.
thanks a lot!

**Comment by hagenburger** [comment]
Maybe v2 needs to be released soon to fix that :) Not sure if I will find time though.
