### ISSUE TITLE
Always parse data as YAML

### ISSUE THREAD

**Issue by hagenburger** [livingstyleguide/livingstyleguide#149]
As JSON is a subset of YAML we don’t need to define the format.

**Comment by myabc** [comment]
:+1:

**Comment by myabc** [comment]
Related: for security reasons, we should probably also be loading YAML with `safe_load`.

**Comment by hagenburger** [comment]
Merged and released in [v2.0.0.alpha.9](https://github.com/livingstyleguide/livingstyleguide/releases/tag/v2.0.0.alpha.9).
