### ISSUE TITLE
Colors will not work if the color variable has an underscore

### ISSUE THREAD

**Issue by cb-josh-c** [livingstyleguide/livingstyleguide#175]
When variable names have an underscore, only the name is parsed and displayed using Colors.
![screen shot 2015-09-09 at 2 44 53 pm](https://cloud.githubusercontent.com/assets/11300831/9772367/59c24db6-5701-11e5-9eb2-46070a3a2b78.png)

**Comment by anxhe** [comment]
Ponle, Hi @cb-josh-c  could you provide the code for this example? I can't reproduce it :
- This is my sass file

        $red_prueba: #AA3939;
        $black: black;

- And this is my lsg code:

        @colors:
          - - - - -
          - - $black $red_prueba  -

Result:

![](https://www.evernote.com/l/AjZ-ck08pYtCRrP8N5oeE8ZDiCSxF4Ws0ykB/image.png)

**Comment by cb-josh-c** [comment]
Yeah, no problem. 
In my sass file: 
<code>$error_red:            #B22828;
</code>
And in my .md file:
<code>@colors:
$error_red
</code>

And when I change $error_red to our main red variable, $red, it works.
![screen shot 2015-10-13 at 9 04 20 am](https://cloud.githubusercontent.com/assets/11300831/10456946/783aecf6-7189-11e5-8a82-93a719e0d619.png)
![screen shot 2015-10-13 at 9 04 31 am](https://cloud.githubusercontent.com/assets/11300831/10456945/783ac1f4-7189-11e5-99f6-3faea7b5fa95.png)

**Comment by anxhe** [comment]
Thanks you , I have tried reproduce the error with your example but I can't reproduce it. Could you say me which version you use?

**Comment by cb-josh-c** [comment]
I am using version 1.2.2 with rails 4.2.3


<http://collectivebias.com>
*Josh Chitty | Developer * <http://collectivebias.com>
joshchitty@collectivebias.com | 1-479-365-0620 (m)

Twitter: *@joshfromcb <http://twitter.com/joshfromcb>*

**Comment by cb-josh-c** [comment]
Awesome, thanks.

**Comment by hagenburger** [comment]
Was tricky, god catch ;) I’ll release it asap.
