### ISSUE TITLE
Colors - "Alt + click to copy Hex code" does not work

### ISSUE THREAD

**Issue by mortro** [livingstyleguide/livingstyleguide#176]
In the colors section "Click to copy variable" works but not "Alt + click to copy Hex code"
It seems like nothing is happening.

Ubuntu 14.04 | Chrome Version 45.0.2454.85 (64-bit)

**Comment by benfrasersimpson** [comment]
It appears that most Linux window manager intercept Alt + click as the keyboard shortcut for moving windows. There is another project with a similar issue [here](https://github.com/gitterHQ/gitter/issues/598) . As a workaround we could re-map this shortcut in LSG to shift + click ?

**Comment by hagenburger** [comment]
Fixed in alpha/pre release.
