### ISSUE TITLE
Sass::SyntaxError: File to import not found or unreadable: livingstyleguide

### ISSUE THREAD

**Issue by floriank** [livingstyleguide/livingstyleguide#189]
Hey,

after a good experience with the styleguide in OpenProject, I decided to give the latest alpha a spin. I followed the guidelines for rails and everything seems fine so far, but when I actually try to look at the rendered Styleguide, it throws a `SyntaxError` in my face:

```bash
Sass::SyntaxError: File to import not found or unreadable: livingstyleguide
# stacktrace with LoadPaths redacted
```

Funnily enough, the `livingstyleguide` is not in the load path. After checking back with my colleagues and some digging in the codebase I arrived at the conclusion that we do not override anything in that regard.

LSG is installed a a dependency in the Gemfile.

I am currently using `v2.0.0.alpha.11` as my version in combination with Rails `v.4.2.5.1`, `sass-rails` is `v5.0.4`.

Any tips or things I might try or could have overlooked?

----

Here is the `styleguide.html.lsg`:

```
// Replace with your default Sass/SCSS file name:
@scss application_bootstrap.scss

// Set the HTML title of the document:
// @title My Living Style Guide

// Import all your style guide files - btw. if you include **/*.lsg here, it includes itself at the moment and throws a StackLevelToodeep error
@import atoms/**/*.lsg
```

**Comment by hagenburger** [comment]
Seems like I need to apply #188 to v2 first before I can try finding out about this. Which version of Sprockets do you use?

**Comment by floriank** [comment]
```
sprockets (2.12.4)
sprockets-rails (2.3.3)
```

Quite old since the codebase is old and large.

**Comment by hagenburger** [comment]
I tried to reproduce this bug, but the versions you mentioned can’t be bundled. Please have a look at the different commit in this example project: https://github.com/livingstyleguide/livingstyleguide-189/commits/master

If I missed any combination, feel free to open a pull request over there. I’m closing the bug for now, but will reopen as soon as I can reproduce it.

(Hint: If you refresh the style guide after checking out commits, be aware Sprockets requires at least a little change (like an empty line) to render a fresh instead a cached version.)

**Comment by floriank** [comment]
Alright, will try once I have the time to do so. Thanks for your effort!
