### ISSUE TITLE
Error when importing normalize-rails

### ISSUE THREAD

**Issue by pzi** [livingstyleguide/livingstyleguide#191]
Hi,

Thanks for a great Gem. I have started using it, but noticed that when I have the following line in my `stylesheet.sass`:

```sass
@import "normalize-rails"
```
https://github.com/markmcconachie/normalize-rails

The stylesheet page falls over as it cannot find that file from the gem:

```
Sass::SyntaxError at /styleguide.html
File to import not found or unreadable: normalize-rails/normalize.
Load paths:
  /Users/patrik/.rvm/gems/ruby-2.3.0@my_project/gems/livingstyleguide-1.4.0/stylesheets
```

If I remove the line, it works just fine. Any idea why this would happen? I am also using the bourbon gem and that one imports fine. Not sure if it would be related to https://github.com/livingstyleguide/livingstyleguide/issues/16.

Cheers
Patrik

**Comment by hagenburger** [comment]
Hey Patrik,

may I know how do you generate the style guide? By the command line or is it integrated into Rails or some other application? Do you use Bundler?

Thanks,

Nico

**Comment by pzi** [comment]
Hey Nico,

I am using it integrated in the Rails app. Installed the gem using bundler, have the `styleguide.html.lsg` in my `stylesheets` directory and added it to `assets.precompile`.

Hope this helps.

Cheers
Patrik

**Comment by pzi** [comment]
Actually, I just noticed that I get errors for every `@import` that is supposed to import styles from a gem or vendor file that is written in plain `.css` instead of `.scss` or `.sass`.

My Rails application is using Sass indented syntax.

**Comment by hagenburger** [comment]
Could you send me your Gemfile please? I’ll try to run an app with the same setup.

**Comment by pzi** [comment]
```rb
source 'https://rubygems.org'

gem 'rails'

# Database & ORM
gem 'carrierwave'
gem 'date_validator'
gem 'paranoia'
gem 'pg'
gem 'ransack'
gem 'validates_email_format_of'

# Authentication & Authorization
gem 'devise'
gem 'cancancan'

# Presentation
gem "autoprefixer-rails"
gem 'active_link_to'
gem 'bourbon'
gem 'coffee-rails'
gem 'haml-rails'
gem 'jquery-rails'
gem 'jquery-timepicker-rails'
gem 'kaminari'
gem 'momentjs-rails'
gem 'neat'
gem 'normalize-rails'
gem 'page_title_helper'
gem 'sass-rails'
gem 'selectize-rails'
gem 'simple_form'
gem 'uglifier'
gem 'sass-css-importer'
gem 'livingstyleguide'

# Provides a nice form for Carrierwave
gem 'simple_form_fancy_uploads'

# Misc
gem 'responders'
gem 'uri_query_merger'

# Deployment
# Airbrake 5 is not compatible with tfg_cap
gem 'airbrake', '~> 4'

# These gems are used in seeds
gem 'factory_girl_rails'
gem 'ffaker'
gem 'seed_helper'

group :development do
  gem 'better_errors'
  gem 'frontier_generators', github: "thefrontiergroup/frontier_generators"
  gem 'letter_opener'
  gem 'quiet_assets'
  gem 'web-console'
end

group :development, :test do
  gem 'byebug'
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'rspec-rails'
  gem 'rspec_junit_formatter'
  gem 'simplecov', require: false
  gem 'simplecov-rcov', require: false
end

group :test do
  gem 'database_cleaner'
  gem 'email_spec'
  gem 'shoulda-matchers'
  gem 'timecop'
end

group :staging do
  # Enable "Staging" ribbon on top right corner
  gem 'rack-dev-mark'
end
```

**Comment by emilos** [comment]
I've encountered the same error when using the font-awesome-rails gem, didn't find a solution to it yet though

**Comment by hagenburger** [comment]
@emilos I’m planning to release [version 2.0.0](https://github.com/livingstyleguide/livingstyleguide/tree/v2#readme) as soon as possible. In this has a completely refactored Sass integration. It’s already released as [Pre.3](https://rubygems.org/gems/livingstyleguide/versions/2.0.0.pre.3). I’m planning an upgrade [blog](https://livingstyleguide.org/blog.html) post soon. Let me know, if it works for you or if you have any questions.

**Comment by AntiFish03** [comment]
@hagenburger, I am receiving this issue also, and when trying to use pre.3 I get the following:

`app/assets/stylesheets/styleguide.html.lsg:1: File to import not found or unreadable: livingstyleguide. (Sass::SyntaxError)`  

Gemfile:
``` ruby

source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '>= 5.0.0.beta3', '< 5.1'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.18', '< 0.5'
# Use Puma as the app server
gem 'puma'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0.0.beta1'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster.
# Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5.x'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'bootstrap', '~> 4.0.0.alpha3'
gem 'rails-assets-tether', '>= 1.1.0'
gem 'font-awesome-rails'
gem 'devise',       github: 'plataformatec/devise'
gem 'simple_form',  github: 'plataformatec/simple_form'
gem 'cocoon',       github: 'nathanvda/cocoon'

gem 'paperclip', github: 'thoughtbot/paperclip'
gem 'exifr'

gem 'bower-rails'
gem 'livingstyleguide',
    github: 'livingstyleguide/livingstyleguide', branch: 'v2'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger
  # console
  gem 'byebug'
  gem 'jasmine',        github: 'jasmine/jasmine-gem'
  gem 'simplecov',      github: 'colszowka/simplecov',         require: false
  gem 'simplecov-json', github: 'vicentllongo/simplecov-json', require: false
  gem 'simplecov-rcov', github: 'fguillen/simplecov-rcov',     require: false
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the
  # background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'growl',                require: false
  gem 'guard',                require: false
  gem 'guard-bundler',        require: false
  gem 'guard-cucumber',       require: false
  gem 'guard-pow',            require: false
  gem 'guard-rubocop',        require: false
  gem 'rails_best_practices', require: false
  gem 'rubocop-git',          require: false
  gem 'powder'
end

group :test do
  # Rspec
  gem 'rspec-core',         github: 'rspec/rspec-core'
  gem 'rspec-expectations', github: 'rspec/rspec-expectations'
  gem 'rspec-mocks',        github: 'rspec/rspec-mocks'
  gem 'rspec-support',      github: 'rspec/rspec-support'
  gem 'rspec-rails',        github: 'rspec/rspec-rails'

  # Cucumber
  gem 'capybara'
  gem 'poltergeist'
  gem 'cucumber-rails', require: false

  # factories and mocks
  gem 'factory_girl_rails'
  gem 'webmock'

  # Other
  gem 'timecop'
  gem 'shoulda-matchers'
  gem 'rails-controller-testing'
  gem 'rubocop'
  gem 'rubocop-checkstyle_formatter',
    github: 'vStone/rubocop-checkstyle_formatter',
    branch: 'patch-1',
    require: false
  gem 'database_cleaner', github: 'DatabaseCleaner/database_cleaner'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Comment by hagenburger** [comment]
@AntiFish03 thanks. Maybe it’s Rails 5, I’m not using it right now. I’ll set up a test app.

**Comment by AntiFish03** [comment]
@hagenburger, I managed to get a local copy working by,  using a similar approach to what https://github.com/twbs/bootstrap-rubygem does to add the  asset paths to rails.

**Comment by hagenburger** [comment]
@AntiFish03 great. Would you be up for a pull request? :)

**Comment by AntiFish03** [comment]
It's not pretty...   And i wish I had more time to clean it up for you....  But its a slimmer version of https://github.com/twbs/bootstrap-rubygem/blob/master/lib/bootstrap.rb

**Comment by AntiFish03** [comment]
Mostly copy and paste honestly

**Comment by hagenburger** [comment]
Could you please give it a try? Both, importing `livingstyleguide` and `normalize-rails` works for me.

``` ruby
gem "livingstyleguide",
    github: "livingstyleguide/livingstyleguide",
    branch: "issue-191-error-when-importing-normalize-rails"
```

**Comment by AntiFish03** [comment]
@hagenburger  I have a rough cut of it I am kinda under the gun atm for real work stuff that this isn't related to.  It does work and the tests do pass but there are a ton of warnings for deprecations and such and I didn't write tests for it. Which is why I am not making a PR for it... I wish I could do more and I probably can at another time.

https://github.com/AntiFish03/livingstyleguide/tree/v2-FIX-191

**Comment by hagenburger** [comment]
@AntiFish03 oh, I think my comment was misleading: I already also made a fix and wanted to get feedback: https://github.com/livingstyleguide/livingstyleguide/commit/98beeffd859da4afe4a08ad6b452563fb353ab4e

I’ll have a look at your code. Thanks :)

**Comment by AntiFish03** [comment]
It works for me!

**Comment by pzi** [comment]
That's great news. I am scheduled to work on the project where I encountered that problem for next week. Will give that a go as well unless I get some time on the weekend.

Thanks Nico!

Cheers
Patrik

**Comment by hagenburger** [comment]
Please reopen if you still see this happens. From my perspective it’s fixed.

**Comment by hagenburger** [comment]
If you find the chance to test [2.0.0.pre.4], I would be happy to get feedback, so I could release 2.0.0 soon. Thanks!

[2.0.0.pre.4]: https://github.com/livingstyleguide/livingstyleguide/releases/tag/v2.0.0.pre.4
