### ISSUE TITLE
No support for globbing

### ISSUE THREAD

**Issue by wouter-muller** [livingstyleguide/livingstyleguide#192]
The livingstyleguide looks amazing!

I tried to set it up, but my `application.scss` uses globbing, like this:
```
@import 'abstracts/mixins/*';
```
When i try to run the compiler, i get the following error:
```
(sass):5: File to import not found or unreadable: abstracts/mixins/*. (Sass::SyntaxError)
```
Or am i doing something else wrong? Help would be greatly appreciated!

**Comment by hagenburger** [comment]
Hey Wouter, I just got back from holidays.

This might be an known issue in version 1.x. Do you use Rails?

[Version 2.x](https://github.com/livingstyleguide/livingstyleguide/tree/v2#readme) got a rewritten Sass handling und should handle those cases natively. 2.x is almost ready for a finial release. Do you want to give it a try?

**Comment by wouter-muller** [comment]
Hi! Thanks for your reply!

Yes i use Rails (4), sounds great to use the V2 version!

**Comment by hagenburger** [comment]
Great, let me know!

I’m closing this for now.

**Comment by wouter-muller** [comment]
Where/how can i get v2.x?

**Comment by hagenburger** [comment]
As long as there is no final version, you have to manually set the version in your Gemfile. The latest version is `2.0.0.pre.1`.

``` ruby
# Gemfile
gem "livingstyleguide", "2.0.0.pre.1"
```

See also: https://github.com/livingstyleguide/livingstyleguide/tree/v2#rails-integration

**Comment by wouter-muller** [comment]
Thanks! It works now!
