### ISSUE TITLE
Windows 10: installing livingstyleguide -> 'redcarpet' native gem requires installed build tools

### ISSUE THREAD

**Issue by HansS** [livingstyleguide/livingstyleguide#194]
Hans@HP-HANS C:\Users\Hans                                            Hans@HP-HANS C:\Users\Hans                                            
> gem install livingstyleguide                                        
Fetching: tilt-2.0.4.gem (100%)                                       
Successfully installed tilt-2.0.4                                     
Fetching: thor-0.19.1.gem (100%)                                      
Successfully installed thor-0.19.1                                    
Fetching: sass-3.4.22.gem (100%)                                      
Successfully installed sass-3.4.22                                    
Fetching: redcarpet-3.3.4.gem (100%)                                  
ERROR:  Error installing livingstyleguide:                            
        The 'redcarpet' native gem requires installed build tools.    
                                                                      
Please update your PATH to include build tools or download the DevKit 
from 'http://rubyinstaller.org/downloads' and follow the instructions 
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'

**Comment by hagenburger** [comment]
Could you please add some more details on how I could help you? Did you follow those instructions yet for installing the DevKit yet?

**Comment by hagenburger** [comment]
Is there anything left where I can help? Otherwise I would close this ticket soon.

**Comment by saower** [comment]
thanks ,i resolve the problems
