### ISSUE TITLE
Content duplicated.

### ISSUE THREAD

**Issue by AntiFish03** [livingstyleguide/livingstyleguide#198]
@hagenburger, after you fixed #191 / #189... I am now having an issue where every `.lsg` file is being duplicated in the output.

![image](https://cloud.githubusercontent.com/assets/381196/16125185/1af9caa2-33b8-11e6-8dfc-7d8fe53154d3.png)

**Comment by blim8183** [comment]
I had a similar issue that was solved by using a file naming convention that added underscores before my scss file names.

So when I changed `buttons.scss` and `buttons.lsg` to `_buttons.scss` and `_buttons.lsg`, they stopped appearing twice. 

No clue why that fixed it though...

**Comment by hagenburger** [comment]
@blim8183 thanks for this hint. I think I can solve that. I’m always using underscores in my projects, so that’s most likely why I never experienced that.

**Comment by AntiFish03** [comment]
I have underscores on my file names

**Comment by hagenburger** [comment]
I actually found and issue where duplicate files could happen. Additionally I finished #166. I’m going to release a new pre version. I’m closing this. Reopen if it still happens to you.

**Comment by hagenburger** [comment]
If you find the chance to test [2.0.0.pre.4], I would be happy to get feedback, so I could release 2.0.0 soon. Thanks!

[2.0.0.pre.4]: https://github.com/livingstyleguide/livingstyleguide/releases/tag/v2.0.0.pre.4
