### ISSUE TITLE
Cannot use in combination with sass-json-vars

### ISSUE THREAD

**Issue by alexlawrence** [livingstyleguide/livingstyleguide#206]
When using https://github.com/vigetlabs/sass-json-vars to import JSON files into scss for variable definitions, executing the livingstyleguide compile command results in the following error

```
Message:
    Command failed: bundle exec livingstyleguide compile /opt/sixsteps/styleguide/app_styleguide.lsg
Sass::SyntaxError: File to import not found or unreadable: test.json.
```

The lsg configuration file requires the Ruby library like this: `@require sass-json-vars`

When executing sass with `-r sass-json-vars` the compilation works. 

Is there anything I am missing or not using correctly?

**Comment by hagenburger** [comment]
Is `sass-json-vars` listed in the _Gemfile_? 

Otherwise Sass might require files in a different way. I would need to check it. Do you have an example project somewhere?

**Comment by alexlawrence** [comment]
Yes, `sass-json-vars` is in the Gemfile.

By following your idea with an example project I was able to compile it successfully. So I guess it is not an issue of livingstyleguide. Something seems to be wrong with the @import paths in my scss files.

Closing this since everything is working as expected. Thanks :)
