### ISSUE TITLE
sprockets " *= require " rendered as comments

### ISSUE THREAD

**Issue by joostliketoast** [livingstyleguide/livingstyleguide#210]
Hi i am running into the following problem with using:
`@scss site/application.css.scss`
We use sprockets ` *= require` in that file instead of sass `@import` because of compile times.
But it looks like sprockets is being ignored by lsg because the require's are just added as comments

**Comment by hagenburger** [comment]
Hey @joostliketoast, Sprockets’ `require` is not supported as it looses variables/mixins/… compared to Sass’ own `@import`.

As this question pops up often, I would be open to support it, if somebody wants to contribute :)

**Comment by joostliketoast** [comment]
@hagenburger we use @import only in the partial where the variables and such are actually being referenced. This saves us a lot of compile time and makes it possible to use things like live-reload again.

A nice article about using sprockets and @import
http://blog.teamtreehouse.com/tale-front-end-sanity-beware-sass-import

**Comment by joostliketoast** [comment]
@hagenburger also we would also be willing to contribute :)

**Comment by hagenburger** [comment]
👍 

I’m not using Sprockets in my main projects right now\*. So I’m very happy to assist as I think it would be great to have this implemented!

\* The compile time of < 2 s for a lot of Sass via a Gulp task running in parallel to Rails was good enough comparing to much more than 30 s via Sprockets. The downside: Within LSG files you can’t use the Rails helpers anymore, which is more easy to implement when embedded in Sprockets.

**Comment by joostliketoast** [comment]
@hagenburger I made it so `@scss yourfile.css.scss` now searches for the asset in sprockets.
But would you like a option parameter for this like `@scss yourfile.css.scss type: sprockets`
or that it always loads the file using the sprockets enviroment if `Sprockets` is available?
