### ISSUE TITLE
Rails 5 deprecation warning (another one)

### ISSUE THREAD

**Issue by bryszard** [livingstyleguide/livingstyleguide#214]
Hello, we're using Rails 5 and lsg 2.0.1. We use lsg from few days and we get deprecation warnings when rendering views:

![image](https://cloud.githubusercontent.com/assets/12682792/22244000/18d1dc94-e22a-11e6-8a04-1ca9e21cb600.png)

The only place in our gems when `get_binding` is called / defined (apart from ActiveRecord) is lsg:

![image](https://cloud.githubusercontent.com/assets/12682792/22244089/6ec8a3bc-e22a-11e6-9062-a684f14846e4.png)

Thanks for adjusting that in advance!

**Comment by darrenterhune** [comment]
Pretty sure this is fixed in Rails 5.1.0.beta https://github.com/rails/rails/commit/0189f4db6fe518de8909b66b7f30046bac52dedc

**Comment by bryszard** [comment]
Ok, @darrenterhune thanks for news.

**Comment by bryszard** [comment]
@darrenterhune The problem here is the slug method:

![image](https://cloud.githubusercontent.com/assets/12682792/23793882/c600f040-058d-11e7-82d1-01b80913f425.png)

After I change `::ActiveSupport::Inflector.parameterize(text, "-")` to `::ActiveSupport::Inflector.parameterize(text, separator: "-")` problem dissapears.

**Comment by darrenterhune** [comment]
@hagenburger is there a specific reason to require active supports string inflections here? Other than readability? Wondering if we could simply switch this out, which would have backwards compatibility and not raise deprecation warnings?

``` ruby
def slug(text)
  text.downcase.gsub(/[ _\.\-!\?\(\)\[\]]+/, "-").gsub(/^-|-$/, "")
end
```
