### ISSUE TITLE
@use is broken? (ruby 2.3.4 and rails 5)

### ISSUE THREAD

**Issue by goncalvesjoao** [livingstyleguide/livingstyleguide#217]
Hi guys, first of all, thank you so much for the hard work.

I created a new Rails 5 app with only **livingstyleguide** installed and tried to follow the [https://github.com/livingstyleguide/livingstyleguide#working-with-existing-view-templates](https://github.com/livingstyleguide/livingstyleguide#working-with-existing-view-templates) @use example, but I keep getting this error

```
Errno::ENOENT (No such file or directory):

(erb):1:in `get_binding'
(erb):8:in `get_binding'
```

Rails app in here: [https://github.com/goncalvesjoao/livingstyleguide-rails-example
](https://github.com/goncalvesjoao/livingstyleguide-rails-example)

Am I doing anything wrong, or is it a bug?

**Comment by hagenburger** [comment]
Hey, I checked your code. It might not be a bug but a feature request for load paths. The path needs to be relative to the current file. Also, the type must be specified:

```
@type erb
@use ../../../../views/headline.html.erb
@data {
  "foo": "bar"
}
```

Is working for me. But I agree on it would be more useful the way you tried to write it:

```
@use views/headline.html.erb
@data {
  "foo": "bar"
}
```

If you want to work on improving this, I would be happy to help.

**Comment by goncalvesjoao** [comment]
Thanks @hagenburger!
I see, I blindly followed the readme example and failed to thing outside the box.
Thanks again mate, I'll close this issue and if I come up with a working solution, I'll open a PR instead of an issue.

**Comment by fakefarm** [comment]
I hit the same issue with load path. I tested with and without `@type erb` and it works either way.

**Comment by fakefarm** [comment]
Oops. I stand corrected. I tested out a static template which worked without `@type erb` but when I tried some `<%= erb %>` it didn't work without `@type erb`. Got it. 😄
