### ISSUE TITLE
.lsg Files Using CRLF Line Endings Don't Parse Correctly

### ISSUE THREAD

**Issue by Watercycle** [livingstyleguide/livingstyleguide#230]
Writing CSS with
```css
@scss { ... }
```
in a `.html.lsg` file using `crlf` line endings results in plain text being rendered to the html, and importing a `.lsg` partial that uses that notation results in
```
Sprockets::FileNotFound - couldn't find file '.../app/assets/stylesheets/styleguide/{'
```
This is only really an issue for Windows users and we have Microsoft to thank for that.

Replacing all newlines `\n` in `COMMANDS_REGEXP` with `(\r?\n)` seems to fix it, but there's probably a better solution.

**Comment by hagenburger** [comment]
Thanks for your bug report! 

Another solution I could think of would be first to replace all `\r\n` with `\n` before starting the parsing. As far as I know Ruby does this automatically when reading files.
