### ISSUE TITLE
Show copy button next to colors and variables

### ISSUE THREAD

**Issue by hagenburger** [livingstyleguide/livingstyleguide#24]

**Comment by hagenburger** [comment]
This might be helpful for the implementation: http://updates.html5rocks.com/2015/04/cut-and-copy-commands

**Comment by joiggama** [comment]
@anxhe

**Comment by hagenburger** [comment]
Merged and released in [v2.0.0.alpha.9](https://github.com/livingstyleguide/livingstyleguide/releases/tag/v2.0.0.alpha.9)!
