### ISSUE TITLE
Not compile

### ISSUE THREAD

**Issue by bdadev** [livingstyleguide/livingstyleguide#49]
I think I did everything as explained but does not compile here.

my file `appication.scss`  and same dir i create the file `styleguide.html.lsg`  ok. My file `appication.scss` should be so `appication.css.scss` ?
I tried using that, but the ruby generated an error

My files below

```
assets/sass/_links_list.md
assets/sass/_links_list.scss
```

I'm add require "livingstyleguide" in my config.rb and command line compass watch, but when I open the file styleguide.html.lsg in the browser nothing happens.

Appears only settings file source: application.scss title: "My Living Style Guide"

I need a help please.

**Comment by tannerhodges** [comment]
I'm also having trouble getting this working with Compass. When I run `livingstyleguide compile assets/scss/styleguide.lsg` it doesn't seem to find my configuration.

Instead, it runs with the default configuration and throws errors when files can't be found:

```
/Users/tannerhodges/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions/image_size.rb:31:in `initialize': No such file or directory @ rb_sysopen - ./images/icons/stars.png (Errno::ENOENT)
```

My project structure is similar to @cekerholic:

```
project/
|- app/
|--- webroot/
|----- assets/ (for production)
|- assets/
|--- img/
|--- js/
|--- scss/
|----- global.scss
|----- styleguide.lsg
|- config.rb
```

My `config.rb`:

```
http_path       = '/'
css_dir         = 'app/webroot/assets/css'
sass_dir        = 'assets/scss'
images_dir      = 'assets/img'
javascripts_dir = 'assets/js'
output_style    = :compressed
sourcemap       = true
```

I've tried digging into the source to debug but can't find where you're getting the Compass configuration. The closest I could figure is that it should be coming through with [`options = Compass.configuration.to_sass_plugin_options`](https://github.com/livingstyleguide/livingstyleguide/blob/3b06ba0d99698f8c8b69f4e6af0803d6fb423c7a/lib/livingstyleguide/tilt_template.rb#L21-L22) but can't tell — pretty new to Ruby.

Appreciate any help.

**Comment by hagenburger** [comment]
@tannerhodges: Could you provide me a test project to let me reproduce this?

The Compass configuration is loaded there: https://github.com/livingstyleguide/livingstyleguide/blob/3b06ba0d99698f8c8b69f4e6af0803d6fb423c7a/lib/livingstyleguide/command_line_interface.rb#L41

**Comment by tannerhodges** [comment]
@hagenburger Ah, that makes sense. My errors are getting thrown in the call to [`template.render`](https://github.com/livingstyleguide/livingstyleguide/blob/3b06ba0d99698f8c8b69f4e6af0803d6fb423c7a/lib/livingstyleguide/command_line_interface.rb#L17). Sass compiles [when `css` is referenced in `layout.html.erb`](https://github.com/livingstyleguide/livingstyleguide/blob/3b06ba0d99698f8c8b69f4e6af0803d6fb423c7a/lib/livingstyleguide/templates/layout.html.erb#L14); it looks for my images in `./images`, can't find them, and throws an error.

Here's my test project: https://github.com/tannerhodges/test-livingstyleguide
